routes/web.php
<?php

Route::match(['GET'],'/', 'PublicController@home')->name('home');
Route::match(['GET'],'/about', 'PublicController@about')->name('about');
Route::match(['GET'],'/donate', 'PublicController@donate')->name('donate');


Route::match(['GET'],'/login', 'AuthController@login')->name('auth.login');
Route::match(['GET'],'/logout', 'AuthController@logout')->name('auth.logout');


Route::match(['GET'],'/sso/callback', 'SSOController@callback')->name('sso.callback');
Route::match(['GET'],'/sso/revoke', 'SSOController@revoke')->name('sso.revoke');
Route::match(['GET'],'/sso/refresh', 'SSOController@refresh')->name('sso.refresh');

Route::group(['middleware' => ['auth']], function () {

    Route::match(['GET'], '/dashboard', 'PortalController@dashboard')->name('dashboard');
    Route::match(['GET', 'POST'], '/welcome', 'PortalController@welcome')->name('welcome');

    Route::match(['GET'], '/{member}/overview', 'PortalController@overview')->name('overview')->middleware("authorized");
    Route::match(['GET'], '/{member}/assets', 'PortalController@assets')->name('assets')->middleware("authorized:esi-assets.read_assets.v1");
    Route::match(['GET'], '/{member}/bookmarks', 'PortalController@bookmarks')->name('bookmarks')->middleware("authorized:esi-bookmarks.read_character_bookmarks.v1");
    Route::match(['GET'], '/{member}/clones', 'PortalController@clones')->name('clones')->middleware("authorized:esi-clones.read_clones.v1");
    Route::match(['GET'], '/{member}/contacts', 'PortalController@contacts')->name('contacts')->middleware("authorized:esi-characters.read_contacts.v1");
    Route::match(['GET'], '/{member}/contracts', 'PortalController@contracts')->name('contracts')->middleware("authorized:esi-contracts.read_character_contracts.v1");
    Route::match(['GET'], '/{member}/contract/{contract_id}', 'PortalController@contract')->name('contract.view')->middleware("authorized:esi-contracts.read_character_contracts.v1");
    Route::match(['GET'], '/{member}/contracts/interactions', 'PortalController@contractInteractions')->name('contracts.interactions')->middleware("authorized:esi-contracts.read_character_contracts.v1");
    Route::match(['GET'], '/{member}/mails', 'PortalController@mails')->name('mails')->middleware("authorized:esi-mail.read_mail.v1");
    Route::match(['GET'], '/{member}/mail/{mail_id}', 'PortalController@mail')->name('mail')->middleware("authorized:esi-mail.read_mail.v1");
    Route::match(['GET'], '/{member}/skills', 'PortalController@skills')->name('skillz')->middleware("authorized:esi-skills.read_skills.v1");
    Route::match(['GET'], '/{member}/skills/flyable', 'PortalController@flyable')->name('skillz.flyable')->middleware("authorized:esi-skills.read_skills.v1");
    Route::match(['GET'], '/{member}/skillqueue', 'PortalController@queue')->name('skillqueue')->middleware("authorized:esi-skills.read_skillqueue.v1");
    Route::match(['GET'], '/{member}/wallet/transactions', 'PortalController@wallet_transactions')->name('wallet.transactions')->middleware("authorized:esi-wallet.read_character_wallet.v1");
    Route::match(['GET'], '/{member}/wallet/journal', 'PortalController@wallet_journal')->name('wallet.journal')->middleware("authorized:esi-wallet.read_character_wallet.v1");

    Route::match(['GET'], '/settings', 'SettingController@index')->name('settings.index');
    Route::match(['GET', 'DELETE'], '/settings/token', 'SettingController@token')->name('settings.token');
    Route::match(['GET', 'POST'], '/settings/access', 'SettingController@access')->name('settings.access');
    Route::match(['GET', 'POST'], '/settings/grant/{grant}', 'SettingController@grant')->name('settings.grant');
    Route::match(['GET', 'POST', 'DELETE'], '/settings/urls', 'SettingController@urls')->name('settings.urls');
});


Route::match(['GET'], '/hack', 'HackingController@index');

app/Models/MemberWalletTransaction.php
<?php

namespace ESIK\Models;

use ESIK\Models\ESI\Type;
use Illuminate\Database\Eloquent\Model;

class MemberWalletTransaction extends Model
{
    protected $primaryKey = 'id';
    protected $table = 'member_wallet_transactions';
    public $incrementing = false;
    protected static $unguarded = true;

    protected $dates = [
        'date'
    ];

    protected $with = [
        'client', 'location', 'type'
    ];

    public function client()
    {
        return $this->morphTo('client', 'client_type', 'client_id', 'id');
    }

    public function location()
    {
        return $this->morphTo('location', 'location_type', 'location_id', 'id');
    }

    public function type()
    {
        return $this->hasOne(Type::class, 'id', 'type_id');
    }

    public function journal ()
    {
        return $this->hasOne(MemberWalletJournal::class, 'journal_id', 'journal_ref_id');
    }

    public function getUnitPriceAttribute($price)
    {
        return number_format($price, 2). " ISK";
    }

    public function getQuantityAttribute($quantity)
    {
        return number_format($quantity, 0);
    }

    public function getCreditAttribute()
    {
        return number_format($this->getOriginal('unit_price') * $this->getOriginal('quantity'), 2) . " ISK";
    }

}

app/Http/Controllers/PortalController.php
<?php

namespace ESIK\Http\Controllers;

use Auth, Carbon, Input, Request, Session, Validator;
use ESIK\Models\Member;
use ESIK\Models\SDE\Group;
use ESIK\Models\ESI\{Station, System,Type};
use ESIK\Jobs\Members\GetMemberAssets;
use ESIK\Http\Controllers\DataController;

class PortalController extends Controller
{
    public function __construct()
    {
        $this->dataCont = new DataController;
    }

    public function dashboard ()
    {
        Auth::user()->load('accessee.info', 'jobs');
        if (Request::has('action')) {
            $action = Request::get('action');
            if ($action === "delete_pending_grant") {
                if (Session::has('to')) {
                    if (starts_with(Session::get('to'), url('/settings/grant/'))) {
                        Session::forget('to');
                        Session::flash('alert', [
                            'header' => "Pending Grant Removed Successfully",
                            'message' => "The pending grant has been removed. If you still want to grant access to your data for the character that generated the URL, please navigate back to where you clicked on that URL, and click on it again.",
                            'type' => 'success',
                            'close' => 1
                        ]);
                        return redirect(route('dashboard'));
                    }
                }
            }
        }
        return view('portal.dashboard');
    }

    public function overview ($member)
    {
        $member = Member::findOrFail($member);
        return view('portal.overview', [
            'member' => $member
        ]);
    }

    public function assets ($member)
    {
        $member = Member::findOrFail($member);
        $dbAssets = $member->assets->keyBy('item_id')->toArray();
        $dbAssets = collect($dbAssets)->recursive();
        $assets = collect();
        $locations = collect();
        $dbAssets->each(function ($dbAsset) use (&$dbAssets,&$assets, $locations) {
            if ($dbAssets->has($dbAsset->get('location_id'))) {

                $locationAsset = $dbAssets->get($dbAsset->get('location_id'));
                if (!$locationAsset->has('contents')) {
                    $locationAsset->put('contents', collect());
                }
                $locationAsset->get('contents')->put($dbAsset->get('item_id'), $dbAsset);
            }
            if (!$dbAssets->has($dbAsset->get('location_id'))) {
                $locations->push($dbAsset->get('location_id'));
            }
        });
        $locations = $locations->unique()->values();
        $systems = $locations->filter(function ($location) {
            return $location >= 30000000 && $location < 32000000;
        });
        $stations = $locations->filter(function ($location) {
            return $location >= 60000000 && $location < 64000000;
        });
        $structures = $locations->filter(function ($location) {
            return $location >= 1000000000000 && $location < 2000000000000;
        });

        System::whereIn('id', $systems->toArray())->get()->each(function ($systemInfo) use ($assets, $dbAssets) {
            $assets->put($systemInfo->id, collect([
                'info' => $systemInfo,
                'assets' => $dbAssets->where('location_id', $systemInfo->id)
            ]));
        });

        Station::whereIn('id', $stations->toArray())->get()->each(function ($stationInfo) use ($assets, $dbAssets) {
            $assets->put($stationInfo->id, collect([
                'info' => $stationInfo,
                'assets' => $dbAssets->where('location_id', $stationInfo->id)
            ]));
        });

        $structures->each(function ($structureId) use ($assets, $dbAssets, $member) {
            $structureInfo = $this->dataCont->getStructure($member, $structureId);
            $assets->put($structureId, collect([
                'info' => $structureInfo->payload,
                'assets' => $dbAssets->where('location_id', $structureId)
            ]));
        });

        $assets = $assets->sortBy('info.name');

        return view('portal.assets', [
            'assets' => $assets
        ])->withMember($member);
    }

    public function bookmarks ($member) {
        $member = Member::findOrFail($member);
        $member->load('bookmarkFolders.bookmarks');

        $uniqueLocations = $member->bookmarks->pluck('location')->unique('id')->keyBy('id');

        foreach ($uniqueLocations as $location) {
            $count = $member->bookmarks->where('location_id', $location->id)->count();
            $uniqueLocations->get($location->id)->count = $count;
        }
        $uniqueLocations = $uniqueLocations->sortByDesc('count');

        return view('portal.bookmarks')->withMember($member)->withUniqueLocations($uniqueLocations);
    }

    public function clones ($member)
    {
        $member = Member::findOrFail($member);
        if ($member->scopes->contains(config('services.eve.scopes.readCharacterImplants'))) {
            $member->load('implants.attributes');
        }
        if ($member->scopes->contains(config('services.eve.scopes.readCharacterClones'))) {
            $member->load('clone', 'jumpClones');
        }
        return view('portal.clones')->withMember($member);
    }

    public function contacts ($member)
    {
        $member = Member::findOrFail($member);
        $member->load(['contacts' => function ($query) {
            $where = collect();
            if (Request::has('npc') && Request::get('npc')) {
                $where->push(collect(['contact_id', '>', 0]));
            } else {
                $where->push(collect(['contact_id', '>', 9000000]));
            }

            if (Request::has('standing')) {
                $where->push(collect(['standing', (int)Request::get('standing')]));
            }

            $query->where($where->toArray())->with('info');
        }] ,'contact_labels');
        return view('portal.contacts')->withMember($member);
    }

    public function contracts ($member)
    {
        $member = Member::findOrFail($member);
        $member->load('contracts', 'contracts.issuer.corporation', 'contracts.acceptor', 'contracts.assignee', 'contracts.start', 'contracts.end');
        $contracts = $member->contracts()->paginate(25);
        return view('portal.contracts.list', [
            'contracts' => $contracts
        ])->withMember($member);
    }

    public function contract ($member, $contract_id)
    {
        $member = Member::findOrFail($member);
        $contract = $member->contracts()->where('id', $contract_id)->with('issuer.corporation', 'acceptor', 'assignee', 'start', 'end', 'items')->firstOrFail();
        return view('portal.contracts.view', [
            'contract' => $contract
        ])->withMember($member);
    }

    public function flyable ($member)
    {
        $member = Member::findOrFail($member);
        $skillz = $member->skillz->keyBy('id');
        $shipGroups = Group::where('category_id', 6)->get()->pluck('id');
        $ships = Type::whereIn('group_id', $shipGroups)->where('published', 1)->with('skillAttributes', 'group')->get()->keyBy('id');
        $skillzAttributeMap = collect(config('services.eve.dogma.attributes.skillz.map'));

        $flyable = collect();
        $ships->each(function ($ship) use ($flyable, $skillz, $skillzAttributeMap) {
            $ship->canFly = false;
            $shipAttributes = $ship->skillAttributes->keyBy('attribute_id');

            $skillzAttributeMap->each(function ($skillLevel, $skillId) use ($skillz, $shipAttributes, $ship) {
                if ($shipAttributes->has($skillId) && $shipAttributes->has($skillLevel)) {
                    $requiredSkill = (int)$shipAttributes->get($skillId)->value;
                    $requiredSkillLevel = (int)$shipAttributes->get($skillLevel)->value;
                    if ($skillz->has($requiredSkill) && $skillz->get($requiredSkill)->pivot->active_skill_level >= (int)$requiredSkillLevel) {
                        $ship->canFly = true;
                    } else {
                        $ship->canFly = false;
                        return false;
                    }
                }
            });
            if (!$flyable->has($ship->group_id)) {
                $flyable->put($ship->group_id, collect([
                    'name' => $ship->group->name,
                    'key' => strtolower(implode('_', explode(' ', $ship->group->name))),
                    'ships' => collect([
                        'can' => collect(),
                        'cant' => collect()
                    ])
                ]));
            }
            if ($ship->canFly) {
                $flyable->get($ship->group_id)->get('ships')->get('can')->put($ship->id, $ship);
            } else {
                $flyable->get($ship->group_id)->get('ships')->get('cant')->put($ship->id, $ship);
            }
        });
        return view('portal.skillz.flyable', [
            'flyable' => $flyable
        ])->withMember($member);
    }

    public function mails ($member)
    {
        $member = Member::findOrFail($member);
        $mails = $member->mail();
        if (Request::has('label')) {
            $label = Request::get('label');
            $mails = $mails->whereRaw("FIND_IN_SET('" . $label . "', member_mail_headers.labels)");
        } elseif (Request::has('ml')) {
            $mailing_list_id = Request::get('ml');
            $mails->where('mailing_list_id', $mailing_list_id);
        }
        if (Request::has('unread')) {
            $mails = $mails->where('member_mail_headers.is_read', NULL);
        }
        $mails = $mails->orderby('sent', 'desc')->with('sender')->paginate(50);
        return view('portal.mail.list', [
           'mails' => $mails
       ])->withMember($member);
    }

    public function mail ($member, $id)
    {
        $member = Member::findOrFail($member);

resources/views/portal/wallet/journals.blade.php
@extends('layout.index')

@section('title', 'My Wallet Transactions')

@section('content')
    <div class="container">
        @include('portal.extra.header')
        @include('portal.extra.nav')
        @include('portal.wallet.extra.nav')
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-stripped">
                    <tr>
                        <th>
                            Date
                        </th>
                        <th>
                            Type
                        </th>
                        <th>
                            Amount
                        </th>
                        <th>
                            Balance
                        </th>
                        <th>
                            Description
                        </th>
                    </tr>
                    @foreach($journal as $entry)
                        <tr>
                            <td>
                                {{ $entry->date->format("Y.m.d H:i \EVE") }}
                            </td>
                            <td>
                                {{ $entry->ref_type }}
                            </td>
                            <td>
                                {{ $entry->amount }}
                            </td>
                            <td>
                                {{  $entry->balance }}
                            </td>
                            <td>
                                {{ $entry->description }}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <hr />
        </div>
        <div class="row">
            <div class="col-lg-12">
                <hr />
                <div class="d-flex justify-content-center">
                    {{ $journal->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/portal/wallet/transactions.blade.php
@extends('layout.index')

@section('title', 'My Wallet Transactions')

@section('content')
    <div class="container">
        @include('portal.extra.header')
        @include('portal.extra.nav')
        @include('portal.wallet.extra.nav')
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-stripped">
                    <tr>
                        <th>
                            When
                        </th>
                        <th>
                            Type
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Credit
                        </th>
                        <th>
                            Client
                        </th>
                        <th>
                            Where
                        </th>
                    </tr>
                    @foreach($transactions as $transaction)
                        <tr>
                            <td>
                                {{ $transaction->date->format("Y.m.d H:i \EVE") }}
                            </td>
                            <td>
                                {{ !is_null($transaction->type) ? $transaction->type->name : "Unknown Type ". $transaction->type_id }}
                            </td>
                            <td>
                                {{ $transaction->unit_price }}
                            </td>
                            <td>
                                {{ $transaction->quantity }}
                            </td>
                            <td>
                                {{ $transaction->credit }}
                            </td>
                            <td>
                                {{ !is_null($transaction->client) ? $transaction->client->name : "Unknown Client ". $transaction->client_id }}
                            </td>
                            <td>
                                {{ !is_null($transaction->location) ? $transaction->location->name : "Unknown Location ". $transaction->location_id }}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <hr />
        </div>
        <div class="row">
            <div class="col-lg-12">
                <hr />
                <div class="d-flex justify-content-center">
                    {{ $transactions->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection